[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
average = "0.15.1"
nalgebra = "0.33.2"
rayon = "1.10.0"
regex = "1.11.1"
strum = { version = "0.26.3", features = ["derive"] }
